name: Android CI

on:
  pull_request:
    branches: [ "android" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create local.properties
      working-directory: ./android
      run: |
        touch local.properties
        echo "server.url=\"secret\"" >> local.properties
        echo "server.authorization=\"secret\"" >> local.properties
        echo "base.url=\"secret\"" >> local.properties

    - name: Make gradlew executable
      working-directory: ./android
      run: chmod +x ./gradlew

    - name: Run test
      working-directory: ./android
      run: ./gradlew test

    - name: Run ktlint
      working-directory: ./android
      run: ./gradlew ktlintCheck
